// Trade good IDs + canonical sellprice defines. One source of truth so trade_goods datums,
// /obj/item sellprices, economic_region produces/demands, standing_orders, and event templates
// all reference the same strings and numbers.

// ---- IDs ----
#define TRADE_GOOD_IRON_ORE "IRON_ORE"
#define TRADE_GOOD_COPPER_ORE "COPPER_ORE"
#define TRADE_GOOD_TIN_ORE "TIN_ORE"
#define TRADE_GOOD_COAL "COAL"
#define TRADE_GOOD_STONE "STONE"
#define TRADE_GOOD_CLAY "CLAY"
#define TRADE_GOOD_CINNABAR "CINNABAR"
#define TRADE_GOOD_SALT "SALT"
#define TRADE_GOOD_GLASS_BATCH "GLASS_BATCH"

#define TRADE_GOOD_GOLD_ORE "GOLD_ORE"
#define TRADE_GOOD_SILVER_ORE "SILVER_ORE"

#define TRADE_GOOD_IRON_INGOT "IRON_INGOT"
#define TRADE_GOOD_COPPER_INGOT "COPPER_INGOT"
#define TRADE_GOOD_TIN_INGOT "TIN_INGOT"
#define TRADE_GOOD_STEEL_INGOT "STEEL_INGOT"
#define TRADE_GOOD_GOLD_INGOT "GOLD_INGOT"
#define TRADE_GOOD_SILVER_INGOT "SILVER_INGOT"

#define TRADE_GOOD_TOPER "TOPER"
#define TRADE_GOOD_GEMERALD "GEMERALD"
#define TRADE_GOOD_SAFFIRA "SAFFIRA"
#define TRADE_GOOD_BLORTZ "BLORTZ"
#define TRADE_GOOD_DORPEL "DORPEL"
#define TRADE_GOOD_JADE "JADE"
#define TRADE_GOOD_OPAL "OPAL"
#define TRADE_GOOD_ONYXA "ONYXA"
#define TRADE_GOOD_CERULITE "CERULITE"
#define TRADE_GOOD_HEARTSTONE "HEARTSTONE"
#define TRADE_GOOD_AMBER "AMBER"
#define TRADE_GOOD_CLAMSHELL "CLAMSHELL"
#define TRADE_GOOD_ROSESTONE "ROSESTONE"

#define TRADE_GOOD_WOOD "WOOD"
#define TRADE_GOOD_DENDOR_ESSENCE "DENDOR_ESSENCE"
#define TRADE_GOOD_LUMBER_ESSENCE "LUMBER_ESSENCE"
#define TRADE_GOOD_VISCERA "VISCERA"
#define TRADE_GOOD_SINEW "SINEW"

#define TRADE_GOOD_FIBERS "FIBERS"
#define TRADE_GOOD_CLOTH "CLOTH"
#define TRADE_GOOD_SILK "SILK"
#define TRADE_GOOD_HIDE "HIDE"
#define TRADE_GOOD_FUR "FUR"
#define TRADE_GOOD_CURED_LEATHER "CURED_LEATHER"
#define TRADE_GOOD_ROPE "ROPE"
#define TRADE_GOOD_PAPER "PAPER"

#define TRADE_GOOD_GRAIN "GRAIN"
#define TRADE_GOOD_OATS "OATS"
#define TRADE_GOOD_RICE "RICE"

#define TRADE_GOOD_MEAT "MEAT"
#define TRADE_GOOD_PORK "PORK"
#define TRADE_GOOD_HAM "HAM"
#define TRADE_GOOD_PORK_BELLY "PORK_BELLY"
#define TRADE_GOOD_POULTRY "POULTRY"
#define TRADE_GOOD_RABBIT "RABBIT"
#define TRADE_GOOD_EGG "EGG"
#define TRADE_GOOD_BUTTER "BUTTER"
#define TRADE_GOOD_CHEESE "CHEESE"
#define TRADE_GOOD_FAT "FAT"
#define TRADE_GOOD_TALLOW "TALLOW"
#define TRADE_GOOD_SALUMOI "SALUMOI"
#define TRADE_GOOD_SAUSAGE "SAUSAGE"
#define TRADE_GOOD_DRIED_FISH "DRIED_FISH"
#define TRADE_GOOD_HONEY "HONEY"
#define TRADE_GOOD_BONES "BONES"
#define TRADE_GOOD_MEAT_EXOTIC "MEAT_EXOTIC"
#define TRADE_GOOD_MUSHROOM "MUSHROOM"

#define TRADE_GOOD_APPLE "APPLE"
#define TRADE_GOOD_PEAR "PEAR"
#define TRADE_GOOD_JACKSBERRY "JACKSBERRY"

#define TRADE_GOOD_CALENDULA "CALENDULA"
#define TRADE_GOOD_POPPY "POPPY"
#define TRADE_GOOD_CABBAGE "CABBAGE"
#define TRADE_GOOD_POTATO "POTATO"
#define TRADE_GOOD_ONION "ONION"
#define TRADE_GOOD_CARROT "CARROT"
#define TRADE_GOOD_TURNIP "TURNIP"

#define TRADE_GOOD_FISH_FILET "FISH_FILET"
#define TRADE_GOOD_FISH_MINCE "FISH_MINCE"
#define TRADE_GOOD_SALMON "SALMON"
#define TRADE_GOOD_COD "COD"
#define TRADE_GOOD_CRAB "CRAB"
#define TRADE_GOOD_BASS "BASS"
#define TRADE_GOOD_CARP "CARP"
#define TRADE_GOOD_SOLE "SOLE"
#define TRADE_GOOD_CLAM "CLAM"
#define TRADE_GOOD_LOBSTER "LOBSTER"
#define TRADE_GOOD_SHRIMP "SHRIMP"

#define TRADE_GOOD_GARLICK "GARLICK"
#define TRADE_GOOD_CUCUMBER "CUCUMBER"
#define TRADE_GOOD_EGGPLANT "EGGPLANT"
#define TRADE_GOOD_TOMATO "TOMATO"
#define TRADE_GOOD_PUMPKIN "PUMPKIN"
#define TRADE_GOOD_SUGAR "SUGAR"
#define TRADE_GOOD_COFFEE "COFFEE"
#define TRADE_GOOD_TEA "TEA"
#define TRADE_GOOD_ROCKNUT "ROCKNUT"
#define TRADE_GOOD_BLACKBERRY "BLACKBERRY"
#define TRADE_GOOD_RASPBERRY "RASPBERRY"
#define TRADE_GOOD_STRAWBERRY "STRAWBERRY"
#define TRADE_GOOD_LEMON "LEMON"
#define TRADE_GOOD_LIME "LIME"
#define TRADE_GOOD_TANGERINE "TANGERINE"
#define TRADE_GOOD_PLUM "PLUM"

// Equipment (finished goods, fulfilled via warehouse, never stockpiled)
#define TRADE_GOOD_STEEL_ARMING_SWORD "STEEL_ARMING_SWORD"
#define TRADE_GOOD_STEEL_SHORTSWORD "STEEL_SHORTSWORD"
#define TRADE_GOOD_STEEL_FALCHION "STEEL_FALCHION"
#define TRADE_GOOD_STEEL_MESSER "STEEL_MESSER"
#define TRADE_GOOD_STEEL_SABRE "STEEL_SABRE"
#define TRADE_GOOD_STEEL_MACE "STEEL_MACE"
#define TRADE_GOOD_STEEL_FLANGED_MACE "STEEL_FLANGED_MACE"
#define TRADE_GOOD_STEEL_FLAIL "STEEL_FLAIL"
#define TRADE_GOOD_STEEL_LONGSWORD "STEEL_LONGSWORD"
#define TRADE_GOOD_STEEL_BROADSWORD "STEEL_BROADSWORD"
#define TRADE_GOOD_STEEL_WARHAMMER "STEEL_WARHAMMER"
#define TRADE_GOOD_STEEL_BATTLEAXE "STEEL_BATTLEAXE"
#define TRADE_GOOD_HURLBAT "HURLBAT"
#define TRADE_GOOD_STEEL_GREATSWORD "STEEL_GREATSWORD"
#define TRADE_GOOD_STEEL_HALBERD "STEEL_HALBERD"
#define TRADE_GOOD_STEEL_EAGLEBEAK "STEEL_EAGLEBEAK"
#define TRADE_GOOD_RECURVE_BOW "RECURVE_BOW"
#define TRADE_GOOD_PADDED_GAMBESON "PADDED_GAMBESON"
#define TRADE_GOOD_HEAVY_LEATHER_COAT "HEAVY_LEATHER_COAT"
#define TRADE_GOOD_HARDENED_LEATHER_HELMET "HARDENED_LEATHER_HELMET"
#define TRADE_GOOD_HARDENED_LEATHER_GORGET "HARDENED_LEATHER_GORGET"
#define TRADE_GOOD_HEAVY_LEATHER_GLOVES "HEAVY_LEATHER_GLOVES"
#define TRADE_GOOD_STEEL_CHAINMAIL "STEEL_CHAINMAIL"
#define TRADE_GOOD_STEEL_HAUBERK "STEEL_HAUBERK"
#define TRADE_GOOD_BRIGANDINE "BRIGANDINE"
#define TRADE_GOOD_BRIGANDINE_HEAVY "BRIGANDINE_HEAVY"
#define TRADE_GOOD_STEEL_CUIRASS "STEEL_CUIRASS"
#define TRADE_GOOD_STEEL_COATPLATES "STEEL_COATPLATES"
#define TRADE_GOOD_STEEL_HALFPLATE "STEEL_HALFPLATE"
#define TRADE_GOOD_STEEL_FULLPLATE "STEEL_FULLPLATE"
#define TRADE_GOOD_STEEL_HELM_KNIGHT "STEEL_HELM_KNIGHT"
#define TRADE_GOOD_STEEL_HELM_BASCINET "STEEL_HELM_BASCINET"
#define TRADE_GOOD_STEEL_HELM_KETTLE "STEEL_HELM_KETTLE"
#define TRADE_GOOD_STEEL_MASK "STEEL_MASK"
#define TRADE_GOOD_CHAIN_GLOVES "CHAIN_GLOVES"
#define TRADE_GOOD_PLATE_GAUNTLETS "PLATE_GAUNTLETS"
#define TRADE_GOOD_STEEL_PLATE_LEGS "STEEL_PLATE_LEGS"

// Tailoring (finished)
#define TRADE_GOOD_NOBLECOAT "NOBLECOAT"
#define TRADE_GOOD_SILK_TUNIC "SILK_TUNIC"
#define TRADE_GOOD_SEASONAL_GOWN "SEASONAL_GOWN"
#define TRADE_GOOD_MAID_DRESS "MAID_DRESS"
#define TRADE_GOOD_ROYAL_DRESS "ROYAL_DRESS"
#define TRADE_GOOD_NOBLE_DRESS "NOBLE_DRESS"
#define TRADE_GOOD_VELVET_DRESS "VELVET_DRESS"
#define TRADE_GOOD_PRISTINE_DRESS "PRISTINE_DRESS"
#define TRADE_GOOD_GILDED_DRESS_SHIRT "GILDED_DRESS_SHIRT"
#define TRADE_GOOD_ORNATE_SILK_DRESS "ORNATE_SILK_DRESS"
#define TRADE_GOOD_SILKY_DRESS "SILKY_DRESS"
#define TRADE_GOOD_SPRING_GOWN "SPRING_GOWN"
#define TRADE_GOOD_FALL_GOWN "FALL_GOWN"
#define TRADE_GOOD_WINTER_GOWN "WINTER_GOWN"
#define TRADE_GOOD_LORDLY_CLOAK "LORDLY_CLOAK"
#define TRADE_GOOD_LADY_SHORTCLOAK "LADY_SHORTCLOAK"
#define TRADE_GOOD_FUR_OVERCOAT "FUR_OVERCOAT"
#define TRADE_GOOD_FANCY_HAT "FANCY_HAT"
#define TRADE_GOOD_NOBLE_CHAPERON "NOBLE_CHAPERON"

// Jewelry (finished) - the gem set covers every gemcarving ring/amulet/bracelets/circlet output
#define TRADE_GOOD_AMBER_RING "AMBER_RING"
#define TRADE_GOOD_GOLD_RING "GOLD_RING"
#define TRADE_GOOD_EMERALD_RING "EMERALD_RING"
#define TRADE_GOOD_DIAMOND_RING "DIAMOND_RING"
#define TRADE_GOOD_JADE_RING "JADE_RING"
#define TRADE_GOOD_SHELL_RING "SHELL_RING"
#define TRADE_GOOD_ROSE_RING "ROSE_RING"
#define TRADE_GOOD_ONYXA_RING "ONYXA_RING"
#define TRADE_GOOD_TURQ_RING "TURQ_RING"
#define TRADE_GOOD_CORAL_RING "CORAL_RING"
#define TRADE_GOOD_OPAL_RING "OPAL_RING"
#define TRADE_GOOD_AMBER_AMULET "AMBER_AMULET"
#define TRADE_GOOD_JADE_AMULET "JADE_AMULET"
#define TRADE_GOOD_SHELL_AMULET "SHELL_AMULET"
#define TRADE_GOOD_ROSE_AMULET "ROSE_AMULET"
#define TRADE_GOOD_ONYXA_AMULET "ONYXA_AMULET"
#define TRADE_GOOD_TURQ_AMULET "TURQ_AMULET"
#define TRADE_GOOD_CORAL_AMULET "CORAL_AMULET"
#define TRADE_GOOD_OPAL_AMULET "OPAL_AMULET"
#define TRADE_GOOD_AMBER_BRACELETS "AMBER_BRACELETS"
#define TRADE_GOOD_JADE_BRACELETS "JADE_BRACELETS"
#define TRADE_GOOD_SHELL_BRACELETS "SHELL_BRACELETS"
#define TRADE_GOOD_ROSE_BRACELETS "ROSE_BRACELETS"
#define TRADE_GOOD_ONYXA_BRACELETS "ONYXA_BRACELETS"
#define TRADE_GOOD_TURQ_BRACELETS "TURQ_BRACELETS"
#define TRADE_GOOD_CORAL_BRACELETS "CORAL_BRACELETS"
#define TRADE_GOOD_OPAL_BRACELETS "OPAL_BRACELETS"
#define TRADE_GOOD_AMBER_CIRCLET "AMBER_CIRCLET"
#define TRADE_GOOD_JADE_CIRCLET "JADE_CIRCLET"
#define TRADE_GOOD_SHELL_CIRCLET "SHELL_CIRCLET"
#define TRADE_GOOD_ROSE_CIRCLET "ROSE_CIRCLET"
#define TRADE_GOOD_ONYXA_CIRCLET "ONYXA_CIRCLET"
#define TRADE_GOOD_TURQ_CIRCLET "TURQ_CIRCLET"
#define TRADE_GOOD_CORAL_CIRCLET "CORAL_CIRCLET"
#define TRADE_GOOD_OPAL_CIRCLET "OPAL_CIRCLET"

// Carved gemstone curios - each good accepts the shape in ANY of the 8 gemcarving materials
#define TRADE_GOOD_CARVED_CAMEO "CARVED_CAMEO"
#define TRADE_GOOD_CARVED_FIGURINE "CARVED_FIGURINE"
#define TRADE_GOOD_CARVED_VASE "CARVED_VASE"
#define TRADE_GOOD_CARVED_FANCY_VASE "CARVED_FANCY_VASE"
#define TRADE_GOOD_CARVED_BUST "CARVED_BUST"
#define TRADE_GOOD_CARVED_STATUE "CARVED_STATUE"

// Artificery (finished)
#define TRADE_GOOD_MESS_KIT "MESS_KIT"
#define TRADE_GOOD_BRONZE_PROSTHETIC "BRONZE_PROSTHETIC"
#define TRADE_GOOD_IRON_PROSTHETIC "IRON_PROSTHETIC"
#define TRADE_GOOD_STEEL_PROSTHETIC "STEEL_PROSTHETIC"
#define TRADE_GOOD_VOLTIC_GAUNTLETS "VOLTIC_GAUNTLETS"
#define TRADE_GOOD_ARTIFICED_HALFPLATE "ARTIFICED_HALFPLATE"

// Trapmaking (finished)
#define TRADE_GOOD_MANTRAP "MANTRAP"

// Trophy heads (finished, fulfilled via warehouse)
#define TRADE_GOOD_TROPHY_WHITE_STAG "TROPHY_WHITE_STAG"
#define TRADE_GOOD_TROPHY_MINOTAUR "TROPHY_MINOTAUR"
#define TRADE_GOOD_TROPHY_DIREBEAR "TROPHY_DIREBEAR"
#define TRADE_GOOD_TROPHY_TROLL "TROPHY_TROLL"

// Magical (finished arcana, fulfilled via warehouse)
#define TRADE_GOOD_ENCHSCROLL_BASIC "ENCHSCROLL_BASIC"
#define TRADE_GOOD_ENCHSCROLL_SUPERIOR "ENCHSCROLL_SUPERIOR"
#define TRADE_GOOD_ENCHSCROLL_GREATER "ENCHSCROLL_GREATER"

// Potions (finished alchemy, fulfilled via warehouse by reagent volume, any container)
#define TRADE_GOOD_HEALTH_POTION "HEALTH_POTION"
#define TRADE_GOOD_STRONG_HEALTH_POTION "STRONG_HEALTH_POTION"
#define TRADE_GOOD_MANA_POTION "MANA_POTION"
#define TRADE_GOOD_STRONG_MANA_POTION "STRONG_MANA_POTION"
#define TRADE_GOOD_STAM_POTION "STAM_POTION"
#define TRADE_GOOD_STRONG_STAM_POTION "STRONG_STAM_POTION"
#define TRADE_GOOD_ANTIDOTE_POTION "ANTIDOTE_POTION"
#define TRADE_GOOD_STRONG_ANTIDOTE_POTION "STRONG_ANTIDOTE_POTION"
#define TRADE_GOOD_STRENGTH_POTION "STRENGTH_POTION"
#define TRADE_GOOD_PERCEPTION_POTION "PERCEPTION_POTION"
#define TRADE_GOOD_INTELLIGENCE_POTION "INTELLIGENCE_POTION"
#define TRADE_GOOD_SPEED_POTION "SPEED_POTION"

// ---- Sellprices ----
// Minerals
#define SELLPRICE_IRON_ORE 8
#define SELLPRICE_COPPER_ORE 6
#define SELLPRICE_TIN_ORE 7
#define SELLPRICE_COAL 4
#define SELLPRICE_STONE 2
#define SELLPRICE_CLAY 2
#define SELLPRICE_CINNABAR 5
#define SELLPRICE_SALT 4
#define SELLPRICE_GLASS_BATCH 4

// Precious ores
#define SELLPRICE_GOLD_ORE 50
#define SELLPRICE_SILVER_ORE 80

// Intermediaries
#define SELLPRICE_IRON_INGOT 10
#define SELLPRICE_COPPER_INGOT 7
#define SELLPRICE_TIN_INGOT 8
#define SELLPRICE_STEEL_INGOT 14
#define SELLPRICE_GOLD_INGOT 60
#define SELLPRICE_SILVER_INGOT 80

// Gems
#define SELLPRICE_TOPER 34
#define SELLPRICE_GEMERALD 42
#define SELLPRICE_SAFFIRA 56
#define SELLPRICE_BLORTZ 88
#define SELLPRICE_DORPEL 121
#define SELLPRICE_BLOOD_DIAMOND 188
#define SELLPRICE_JADE 50
#define SELLPRICE_OPAL 80
#define SELLPRICE_ONYXA 30
#define SELLPRICE_CERULITE 75
#define SELLPRICE_HEARTSTONE 60
#define SELLPRICE_AMBER 50
#define SELLPRICE_CLAMSHELL 5
#define SELLPRICE_ROSESTONE 15

// Artisan raws
#define SELLPRICE_WOOD 3
#define SELLPRICE_DENDOR_ESSENCE 20
#define SELLPRICE_VISCERA 3

// Textile / animal products
#define SELLPRICE_FIBERS 2
#define SELLPRICE_CLOTH 3
#define SELLPRICE_SILK 4
#define SELLPRICE_HIDE 8
#define SELLPRICE_FUR 10
#define SELLPRICE_CURED_LEATHER 3
#define SELLPRICE_ROPE 6
#define SELLPRICE_PAPER 6

// Grains
#define SELLPRICE_GRAIN 3
#define SELLPRICE_OATS 3
#define SELLPRICE_RICE 3

// Animal foods
#define SELLPRICE_MEAT 4
#define SELLPRICE_PORK 4
#define SELLPRICE_HAM 6
#define SELLPRICE_PORK_BELLY 5
#define SELLPRICE_POULTRY 4
#define SELLPRICE_RABBIT 3
#define SELLPRICE_EGG 2
#define SELLPRICE_BUTTER 7
#define SELLPRICE_CHEESE 3
#define SELLPRICE_FAT 3
#define SELLPRICE_TALLOW 2
#define SELLPRICE_SALUMOI 9
#define SELLPRICE_SAUSAGE 7
#define SELLPRICE_DRIED_FISH 7

// Fruits
#define SELLPRICE_APPLE 3
#define SELLPRICE_PEAR 3
#define SELLPRICE_JACKSBERRY 3

// Vegetables
#define SELLPRICE_CALENDULA 4
#define SELLPRICE_POPPY 3
#define SELLPRICE_CABBAGE 3
#define SELLPRICE_POTATO 3
#define SELLPRICE_ONION 3
#define SELLPRICE_CARROT 3
#define SELLPRICE_TURNIP 3
#define SELLPRICE_GARLICK 3
#define SELLPRICE_CUCUMBER 3
#define SELLPRICE_EGGPLANT 3
#define SELLPRICE_TOMATO 3
#define SELLPRICE_PUMPKIN 3

// Exotic / luxury produce
#define SELLPRICE_SUGAR 5
#define SELLPRICE_COFFEE 5
#define SELLPRICE_TEA 5
#define SELLPRICE_ROCKNUT 4
#define SELLPRICE_BLACKBERRY 4
#define SELLPRICE_RASPBERRY 4
#define SELLPRICE_STRAWBERRY 4
#define SELLPRICE_LEMON 4
#define SELLPRICE_LIME 4
#define SELLPRICE_TANGERINE 4
#define SELLPRICE_PLUM 4
#define SELLPRICE_HONEY 10

// Seafood
#define SELLPRICE_FISH_FILET 3
#define SELLPRICE_FISH_MINCE 2
#define SELLPRICE_SALMON 4
#define SELLPRICE_COD 4
#define SELLPRICE_CRAB 4
#define SELLPRICE_BASS 4
#define SELLPRICE_CARP 4
#define SELLPRICE_SOLE 4
#define SELLPRICE_CLAM 4
#define SELLPRICE_LOBSTER 4
#define SELLPRICE_SHRIMP 4

// Potions (50dr bottle = one base unit)
#define SELLPRICE_HEALTH_POTION 20
#define SELLPRICE_STRONG_HEALTH_POTION 30
#define SELLPRICE_MANA_POTION 20
#define SELLPRICE_STRONG_MANA_POTION 35
#define SELLPRICE_STAM_POTION 20
#define SELLPRICE_STRONG_STAM_POTION 35
#define SELLPRICE_ANTIDOTE_POTION 20
#define SELLPRICE_STRONG_ANTIDOTE_POTION 40
#define SELLPRICE_BUFF_POTION 48

// Enchantment scrolls
#define SELLPRICE_ENCHSCROLL_BASIC 50
#define SELLPRICE_ENCHSCROLL_SUPERIOR 100
#define SELLPRICE_ENCHSCROLL_GREATER 150
